using LinkScape.Models;

namespace LinkScape.Browser.Components;

internal sealed record BrowserTabRailProps(
    BrowserTab[] Tabs,
    int SelectedIndex,
    string SelectedTabId,
    bool IsTabsCollapsed,
    bool IsLoading,
    Action<int> OnSelect,
    Action<string> OnToggleFavoriteTab,
    Action<string> OnCloseTabFromContextMenu,
    Action<string> OnReloadTab,
    Action<string> OnOpenTabInNewWindow,
    Action<string, int> OnMoveTab,
    Func<BrowserTab, string?> GetTabInstalledWebAppName,
    Func<BrowserTab, string?> GetTabInstallableWebAppName,
    Action<string> OnOpenTabAsWebApp,
    Action<string> OnInstallTabWebApp,
    string ActiveCommandCenterSection,
    bool IsCommandCenterExpanded,
    IReadOnlyList<HistoryItem> MostVisitedItems,
    IReadOnlyList<HistoryItem> RecentHistoryItems,
    string HistoryFilter,
    int HistoryLimit,
    string HistoryImportStatus,
    IReadOnlyDictionary<string, BrowserImportProfile[]> HistoryImportBrowserProfiles,
    IReadOnlyList<FavoriteItem> FavoriteItems,
    int FavoritesLimit,
    IReadOnlyList<TabCollection> TabCollections,
    IReadOnlyList<TabCollectionItem> CollectionItems,
    IReadOnlyDictionary<string, string[]> CollectionMembership,
    string CollectionName,
    string CollectionStatus,
    string FavoritesFilter,
    string FavoritesImportStatus,
    IReadOnlyDictionary<string, BrowserImportProfile[]> FavoritesImportBrowserProfiles,
    bool IsCommandCenterBusy,
    bool IsCommandCenterHighlighted,
    string CommandCenterBusyText,
    IReadOnlyDictionary<string, string> SettingsSnapshot,
    Action<string, string> OnSaveSettingValue,
    Action<string> OnHistoryFilterChanged,
    Action OnLoadMoreHistory,
    Action<string> OnFavoritesFilterChanged,
    Action OnLoadMoreFavorites,
    Action<string> OnCollectionNameChanged,
    Action OnCreateCollection,
    Action OnDeleteCollection,
    Action OnAddCurrentTabToCollection,
    Action<string, string, string> OnAddUrlToCollection,
    Action OnSetStartupCollection,
    Action OnImportHistory,
    Action<string> OnImportBrowserHistory,
    Action<string, string> OnImportBrowserHistoryProfile,
    Action OnDeleteAllHistory,
    Action OnImportFavorites,
    Action<string> OnImportBrowserFavorites,
    Action<string, string> OnImportBrowserFavoritesProfile,
    Action OnDeleteAllFavorites,
    Action<string> OnOpenHistoryItem,
    Action<string> OnOpenHistoryItemInNewTab,
    Action<string> OnDeleteHistoryItem,
    Action<string> OnOpenFavoriteItemInNewTab,
    Action<string> OnOpenFavoriteItem,
    Action<string> OnDeleteFavoriteItem,
    Action<string> OnOpenCollectionItem,
    Action<string> OnOpenCollectionItemInNewTab,
    Action<string> OnRemoveCollectionItem,
    Action<string, int> OnMoveCollectionItem,
    Action<string> OnToggleCommandCenter,
    Action OnToggleCommandCenterExpanded,
    bool IsRailTabsExpanded,
    Action OnMaximizeTabs,
    Action OnMinimizeTabs,
    Action OnDismissCommandCenter,
    Action OnRailTransitionCompleted);

internal sealed class BrowserTabRail : Component<BrowserTabRailProps>
{
    public override Element Render() =>
        BrowserChrome.BuildTabRail(
            Props.Tabs,
            Props.SelectedIndex,
            Props.SelectedTabId,
            Props.IsTabsCollapsed,
            Props.IsLoading,
            Props.OnSelect,
            Props.OnToggleFavoriteTab,
            Props.OnCloseTabFromContextMenu,
            Props.OnReloadTab,
            Props.OnOpenTabInNewWindow,
            Props.OnMoveTab,
            Props.GetTabInstalledWebAppName,
            Props.GetTabInstallableWebAppName,
            Props.OnOpenTabAsWebApp,
            Props.OnInstallTabWebApp,
            Props.ActiveCommandCenterSection,
            Props.IsCommandCenterExpanded,
            Props.MostVisitedItems,
            Props.RecentHistoryItems,
            Props.HistoryFilter,
            Props.HistoryLimit,
            Props.HistoryImportStatus,
            Props.HistoryImportBrowserProfiles,
            Props.FavoriteItems,
            Props.FavoritesLimit,
            Props.TabCollections,
            Props.CollectionItems,
            Props.CollectionMembership,
            Props.CollectionName,
            Props.CollectionStatus,
            Props.FavoritesFilter,
            Props.FavoritesImportStatus,
            Props.FavoritesImportBrowserProfiles,
            Props.IsCommandCenterBusy,
            Props.IsCommandCenterHighlighted,
            Props.CommandCenterBusyText,
            Props.SettingsSnapshot,
            Props.OnSaveSettingValue,
            Props.OnHistoryFilterChanged,
            Props.OnLoadMoreHistory,
            Props.OnFavoritesFilterChanged,
            Props.OnLoadMoreFavorites,
            Props.OnCollectionNameChanged,
            Props.OnCreateCollection,
            Props.OnDeleteCollection,
            Props.OnAddCurrentTabToCollection,
            Props.OnAddUrlToCollection,
            Props.OnSetStartupCollection,
            Props.OnImportHistory,
            Props.OnImportBrowserHistory,
            Props.OnImportBrowserHistoryProfile,
            Props.OnDeleteAllHistory,
            Props.OnImportFavorites,
            Props.OnImportBrowserFavorites,
            Props.OnImportBrowserFavoritesProfile,
            Props.OnDeleteAllFavorites,
            Props.OnOpenHistoryItem,
            Props.OnOpenHistoryItemInNewTab,
            Props.OnDeleteHistoryItem,
            Props.OnOpenFavoriteItemInNewTab,
            Props.OnOpenFavoriteItem,
            Props.OnDeleteFavoriteItem,
            Props.OnOpenCollectionItem,
            Props.OnOpenCollectionItemInNewTab,
            Props.OnRemoveCollectionItem,
            Props.OnMoveCollectionItem,
            Props.OnToggleCommandCenter,
            Props.OnToggleCommandCenterExpanded,
            Props.IsRailTabsExpanded,
            Props.OnMaximizeTabs,
            Props.OnMinimizeTabs,
            Props.OnDismissCommandCenter,
            Props.OnRailTransitionCompleted);
}
