using LinkScape.Models;

namespace Browser.Components;

internal sealed record BrowserTabRailProps(
    BrowserTab[] Tabs,
    int SelectedIndex,
    string SelectedTabId,
    bool IsTabsCollapsed,
    bool IsLoading,
    Action<int> OnSelect,
    Action<string> OnToggleFavoriteTab,
    Action<string> OnCloseTabFromContextMenu,
    Action<string> OnReloadTab,
    string ActiveCommandCenterSection,
    bool IsCommandCenterExpanded,
    IReadOnlyList<HistoryItem> MostVisitedItems,
    IReadOnlyList<HistoryItem> RecentHistoryItems,
    string HistoryFilter,
    string HistoryImportStatus,
    IReadOnlyList<string> HistoryImportBrowserNames,
    IReadOnlyList<FavoriteItem> FavoriteItems,
    string FavoritesFilter,
    string FavoritesImportStatus,
    IReadOnlyList<string> FavoritesImportBrowserNames,
    bool IsCommandCenterBusy,
    bool IsCommandCenterHighlighted,
    string CommandCenterBusyText,
    IReadOnlyDictionary<string, string> SettingsSnapshot,
    Action<string, string> OnSaveSettingValue,
    Action<string> OnHistoryFilterChanged,
    Action<string> OnFavoritesFilterChanged,
    Action OnImportHistory,
    Action<string> OnImportBrowserHistory,
    Action OnDeleteAllHistory,
    Action OnImportFavorites,
    Action<string> OnImportBrowserFavorites,
    Action OnDeleteAllFavorites,
    Action<string> OnOpenHistoryItem,
    Action<string> OnOpenHistoryItemInNewTab,
    Action<string> OnDeleteHistoryItem,
    Action<string> OnOpenFavoriteItemInNewTab,
    Action<string> OnOpenFavoriteItem,
    Action<string> OnDeleteFavoriteItem,
    Action<string> OnToggleCommandCenter,
    Action OnToggleCommandCenterExpanded,
    bool IsRailTabsExpanded,
    Action OnMaximizeTabs,
    Action OnMinimizeTabs,
    Action OnDismissCommandCenter,
    Action OnRailTransitionCompleted);

internal sealed class BrowserTabRail : Component<BrowserTabRailProps>
{
    public override Element Render() =>
        BrowserChrome.BuildTabRail(
            Props.Tabs,
            Props.SelectedIndex,
            Props.SelectedTabId,
            Props.IsTabsCollapsed,
            Props.IsLoading,
            Props.OnSelect,
            Props.OnToggleFavoriteTab,
            Props.OnCloseTabFromContextMenu,
            Props.OnReloadTab,
            Props.ActiveCommandCenterSection,
            Props.IsCommandCenterExpanded,
            Props.MostVisitedItems,
            Props.RecentHistoryItems,
            Props.HistoryFilter,
            Props.HistoryImportStatus,
            Props.HistoryImportBrowserNames,
            Props.FavoriteItems,
            Props.FavoritesFilter,
            Props.FavoritesImportStatus,
            Props.FavoritesImportBrowserNames,
            Props.IsCommandCenterBusy,
            Props.IsCommandCenterHighlighted,
            Props.CommandCenterBusyText,
            Props.SettingsSnapshot,
            Props.OnSaveSettingValue,
            Props.OnHistoryFilterChanged,
            Props.OnFavoritesFilterChanged,
            Props.OnImportHistory,
            Props.OnImportBrowserHistory,
            Props.OnDeleteAllHistory,
            Props.OnImportFavorites,
            Props.OnImportBrowserFavorites,
            Props.OnDeleteAllFavorites,
            Props.OnOpenHistoryItem,
            Props.OnOpenHistoryItemInNewTab,
            Props.OnDeleteHistoryItem,
            Props.OnOpenFavoriteItemInNewTab,
            Props.OnOpenFavoriteItem,
            Props.OnDeleteFavoriteItem,
            Props.OnToggleCommandCenter,
            Props.OnToggleCommandCenterExpanded,
            Props.IsRailTabsExpanded,
            Props.OnMaximizeTabs,
            Props.OnMinimizeTabs,
            Props.OnDismissCommandCenter,
            Props.OnRailTransitionCompleted);
}
